### ISSUE TITLE
Files missing from JAR

### ISSUE THREAD

**Issue by la289** [ProjectMapK/KMapper#51]
`java.lang.NoClassDefFoundError: com/mapk/core/KFunctionForCallKt`

![image](https://user-images.githubusercontent.com/18703943/139160216-4dfe8203-5037-47ce-aa8b-30c3e72e64f0.png)

**Comment by k163377** [comment]
That file is defined in the common module.
https://github.com/ProjectMapK/Shared

**Comment by k163377** [comment]
I may have misunderstood the intent of the issue you gave me.

Maybe it's a bug on the `JitPack` side, but it looks like the `Shared` module specified as `api` in `build.gradle` is not actually being downloaded.

You can fix this problem by manually specifying `com.github.ProjectMapK:Shared` in `build.gradle`.
Please see the following file for the version to specify.
https://github.com/ProjectMapK/KMapper/blob/master/build.gradle.kts
