### ISSUE TITLE
KMapper for copy constructor (Question / Feature request)

### ISSUE THREAD

**Issue by ghost** [ProjectMapK/KMapper#52]
I am currently looking for a Kotlin object mapping framework as this one, which looks great by the way !

With all framework I looked at, I miss the following functionality : mapping for copy constructor
- Let's say I have 2 data classes A and B
- This framework allows me to create an instance of A from an instance of B
- I'd also like to be able to copy A instance updated with non-null properties of B instance.
> Creation and copy mapping rules would be identical.

Do I miss an obvious way to achieve this ?
Or would it be interresting to add such functionality ?

Thanks & regards,
Renaud

**Comment by k163377** [comment]
@renaud-twd 
I'm sorry, but I couldn't read what you were trying to do.

With `KMapper`, you can do something like the following sample code.
Is this the correct operation you are looking for?

```kotlin
import com.mapk.annotations.KParameterRequireNonNull
import com.mapk.kmapper.KMapper

data class A(@param:KParameterRequireNonNull val foo: Int, @param:KParameterRequireNonNull val bar: Int)
data class B(val foo: Int?, val bar: Int?)

fun main() {
    val mapper = KMapper<A>()

    val srcB = B(1, null)
    val srcA = A(10, 11)

    val result: A = mapper.map(srcB, srcA)

    println(result) // -> A(foo=1, bar=11)
}
```

**Comment by ghost** [comment]
Thanks for your answer @k163377 !
That's exactly what I was looking for.
:+1:

**Comment by ghost** [comment]
Hello again @k163377 !

I have another question/issue about your framework.
I wanted to use KMapper to map objects that belongs to packages I do not own.
Thus I can't add annotations neither in the source nor in the destination classes.

Is there a way to declare parameters aliases and conversions directly in the mapper définition rather than using annotations ?

For example, it could be something like:
```
import com.mapk.annotations.KParameterRequireNonNull
import com.mapk.kmapper.KMapper

import com.xxx.A         // data class A(val foo: Int, val bar: Int)
import com.xxx.B         // data class B(val fooAlias: Int?, val bar: Int?)

fun main() {
    val mapper = KMapper<A>()
                             .aliases(A::foo, listOf("fooAlias", "fooAlias2"))
                             .requireNotNull(A::foo)

    val srcB = B(1, null)
    val srcA = A(10, 11)
    val result: A = mapper.map(srcB, srcA)

    println(result) // -> A(foo=1, bar=11)
}
```

Best regards,
Renaud

**Comment by k163377** [comment]
It is not easy to support because it is an additional feature.
Also, I am too busy working on another project to spend time maintaining this project.

**Comment by ghost** [comment]
Sure, I understand perfectly !
Thank you for your time.
