### ISSUE TITLE
Can KMapper work with non data classes ?

### ISSUE THREAD

**Issue by ghost** [ProjectMapK/KMapper#53]
Hello again,

I try to use KMapper with Spring to map some Data Transfer Objects to JPA entitites.
I have an issue as a JPA Entity cannot be declared as a `data class` (this is a limitation of the Spring framework).

Is there any chance that KMapper would work with standard classes ?

I currently end up with following error:
```
com/mapk/core/KFunctionForCallKt
java.lang.NoClassDefFoundError: com/mapk/core/KFunctionForCallKt
	at com.mapk.kmapper.KMapper.<init>(KMapper.kt:27)
	at com.mapk.kmapper.KMapper.<init>(KMapper.kt:26)
```

Thanks & regards,
Renaud

**Comment by k163377** [comment]
> Is there any chance that KMapper would work with standard classes ?

If the `Class` is defined in `Kotlin`, it should be executable by specifying a callable `KFunction` or by using the `KConstructor` annotation (top-level functions, etc. can also be called).

> I currently end up with following error:

It would be helpful if you could post the code you are running and the complete stack trace.
This error is probably happening in the `Shared` module, but I couldn't figure out the cause from your situation.

You may want to try installing the `Shared` module separately, as it may cause the following problems.
https://github.com/ProjectMapK/KMapper/issues/51#issuecomment-1023948629

**Comment by ghost** [comment]
Thanks for your answer.
I'm sorry, I do not have anymore time to dig into this issue. I must have misused your library. :)
Thanks again for your time and support.
